version: '2.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.43.77
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  discovery-service:
    build: EurekaServer
    image: karasatishkumar/discovery-service
    container_name: discovery-service
    restart: always
    depends_on:
      - kafka
    ports:
      - 8761:8761
    
  config-server:
    build: ConfigServer
    image: karasatishkumar/config-server
    container_name: config-server
    restart: always
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - 8888:8888

  email-service:
    build: EmailService
    image: karasatishkumar/email-service
    container_name: email-service
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 8083:8083
    links:
      - discovery-service:discovery-service

  user-service:
    build: UserAccount
    image: karasatishkumar/user-service
    container_name: user-service
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 8084:8084
    links:
      - discovery-service:discovery-service
