spring:
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/karasatishkumar/streaming-lab.git/
          search-paths:
              - "user-registration/EmailServiceConfigProperties/{application}/{profile}"