spring:
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/karasatishkumar/streaming-lab.git/
          search-paths:
              - "partition-consumer-assignment/config-properties/{application}/{profile}"

eureka:
  instance:
   hostname: eureka-server
   port: 8761

  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    register-with-eureka: true
    fetch-registry: true